apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.application.name }}-pubsub-jetstream-invoke
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: natsURL
      value: {{ .Values.nats.url | quote}}
    - name: jwt
      value: {{ .Values.nats.jwt | quote}}
    - name: seedKey
      value: {{ .Values.nats.seedKey | quote}}
    - name: durableName
      value: "invoke-{{ .Values.application.name }}-consumer"
    - name: queueGroupName
      value: "invoke-{{ .Values.application.name }}-consumer"
scopes:
  - {{ .Values.application.name }}
