apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.application.name }}-pubsub-jetstream-invoke
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: name
      value: "my-conn-name"
    - name: streamName
      value: "invoke-all"
    - name: natsURL
      value: {{ .Values.nats.url | quote}}
    - name: jwt
      value: {{ .Values.nats.jwt | quote}}
    - name: seedKey
      value: {{ .Values.nats.seedKey | quote}}
#    - name: "deliverPolicy"
#      value: all
    - name: durableName
#      k8s-quarkus-tpl-consumer
      value: "k8s-{{ .Values.application.name }}-consumer"
    - name: queueGroupName
#      #      k8s-quarkus-tpl-queue
      value: "k8s-{{ .Values.application.name }}-queue"
scopes:
  - {{ .Values.application.name }}
