apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.application.name }}-statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: {{ .Values.redis.url | quote }}
    - name: redisPassword
      value: {{ .Values.redis.password | quote }}
    - name: actorStateStore
      value: {{ .Values.redis.actorStateStore | quote }}
scopes:
  - {{ .Values.application.name }}
