apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.application.name }}-sub
spec:
  topic: invoke.>
  route: /dapr/subscribe/callback/service_invoke
  pubsubname: {{ .Values.application.name }}-pubsub-jetstream-invoke
scopes:
  - {{ .Values.application.name }}